In [30]:
import pandas as pd
import numpy as np
insurance=pd.read_csv('Insurance_new.csv')
insurance['target'].value_counts(normalize=True)

y=insurance['target']
insurance.drop(columns=['target','id'],inplace=True)

insurance=insurance.replace(to_replace=-1,value=np.nan)

#insurance.isnull().sum()

In [31]:
missing_values=pd.DataFrame({'Column Name':insurance.columns,'Missing Values Count':insurance.isnull().sum(),
                            'Missing values percentage':insurance.isnull().sum()/insurance.shape[0]*100})

cols_to_drop=list(missing_values[missing_values['Missing values percentage']>50].index)
insurance.drop(columns=cols_to_drop,inplace=True)

In [32]:
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

x_train,x_test,y_train,y_test=train_test_split(insurance,y,test_size=0.3,random_state=42)


In [33]:
for col in x_train.columns.values:
    if x_train[col].isnull().sum()!=0:
        if '_cat' in col:
            x_train[col].fillna(x_train[col].mode()[0], inplace=True)
            x_test[col].fillna(x_train[col].mode()[0], inplace=True)
        elif x_train[col].dtype=='int64':
            x_train[col].fillna(x_train[col].mode()[0], inplace=True)
            x_test[col].fillna(x_train[col].mode()[0], inplace=True)
        else:
            x_train[col].fillna(x_train[col].mean(), inplace=True)
            x_test[col].fillna(x_train[col].mean(), inplace=True)
            
            

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score,precision_score,recall_score

log_reg=LogisticRegression()
log_reg.fit(x_train,y_train)

y_log_reg_pred=log_reg.predict(x_test)

print(confusion_matrix(y_test,y_log_reg_pred))
print('Accuracy score:', accuracy_score(y_test,y_log_reg_pred))
print('Recall:', recall_score(y_test,y_log_reg_pred))
print('Precision:', precision_score(y_test,y_log_reg_pred))
print('F1 score:', f1_score(y_test,y_log_reg_pred))

[[14446     0]
 [  554     0]]
Accuracy score: 0.9630666666666666
Recall: 0.0
Precision: 0.0
F1 score: 0.0


In [50]:
from imblearn.over_sampling import SMOTE

sm= SMOTE(random_state=2,sampling_strategy=0.5)
x_train_res,y_train_res=sm.fit_sample(x_train,y_train)

In [51]:
log_reg1=LogisticRegression()
log_reg1.fit(x_train_res,y_train_res)

y_pred=log_reg1.predict(x_test)

print(confusion_matrix(y_test,y_pred))
print('Accuracy score:', accuracy_score(y_test,y_pred))
print('Recall:', recall_score(y_test,y_pred))
print('Precision:', precision_score(y_test,y_pred))
print('F1 score:', f1_score(y_test,y_pred))

[[14408    38]
 [  549     5]]
Accuracy score: 0.9608666666666666
Recall: 0.009025270758122744
Precision: 0.11627906976744186
F1 score: 0.01675041876046901


In [54]:
from sklearn.tree import DecisionTreeClassifier

dt=DecisionTreeClassifier()

dt.fit(x_train_res,y_train_res)

y_dt_pred=dt.predict(x_test)

print(confusion_matrix(y_test,y_dt_pred))
print('Accuracy score:',accuracy_score(y_test,y_dt_pred))
print('Recall:',recall_score(y_test,y_dt_pred))
print('Precision:',precision_score(y_test,y_dt_pred))
print('F1 score:', f1_score(y_test,y_dt_pred))

[[13755   691]
 [  515    39]]
Accuracy score: 0.9196
Recall: 0.0703971119133574
Precision: 0.05342465753424658
F1 score: 0.06074766355140187


In [59]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(random_state=54)

rf.fit(x_train_res,y_train_res)

y_rf_pred=rf.predict(x_test)

print(confusion_matrix(y_test,y_rf_pred))
print('Accuracy score:',accuracy_score(y_test,y_rf_pred))
print('Recall:',recall_score(y_test,y_rf_pred))
print('Precision:',precision_score(y_test,y_rf_pred))
print('F1 score:', f1_score(y_test,y_rf_pred))

[[14442     4]
 [  553     1]]
Accuracy score: 0.9628666666666666
Recall: 0.0018050541516245488
Precision: 0.2
F1 score: 0.0035778175313059034
